name: Build Pages
description: ""

outputs:
  artifact_id:
    value: ${{ steps.upload-artifact.outputs.artifact_id }}
    description: "The upload ID of the build artifact"
runs:
  using: "composite"
  steps:
    - name: Is Git Branch "^renovate/ruby-[0-9]+[.]x$?"
      id: isGitBranchRenovateRuby
      shell: bash
      run: |
        v=$(if [[ "$(git branch --show-current)"  =~ ^renovate/ruby-[0-9]+[.]x$ ]];
          then echo true;
          else echo false;
          fi;
        );
        echo "v=$v" >> "$GITHUB_OUTPUT"

    - name: dbg
      shell: bash
      run: |
        echo "currentGitBranch: $(git branch --show-current)
        phrase: '^renovate/ruby-[0-9]+[.]x$'
        BUNDLE_FROZEN: ${{ !steps.isGitBranchRenovateRuby.outputs.v }}
        "

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
      env:
        BUNDLE_FROZEN: ${{ !steps.isGitBranchRenovateRuby.outputs.v }}

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v6

    - name: Build with Jekyll
      shell: bash
      # Outputs to the './_site' directory by default
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production

    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v4
      id: upload-artifact
