name: Build Pages
description: ""

outputs:
  artifact_id:
    value: ${{ steps.upload-artifact.outputs.artifact_id }}
runs:
  using: "composite"
  steps:
    - name: dbg
      run: |
        echo "github.ref_name: ${{ github.ref_name }}\
        phrase: renovate/ruby-\
        unfreeze_lockfile: ${{ !startsWith( github.ref_name, 'renovate/ruby-' ) }}"

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
      env:
        BUNDLE_FROZEN: ${{ !startsWith( github.ref_name, 'renovate/ruby-') }}

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Build with Jekyll
      shell: bash
      # Outputs to the './_site' directory by default
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production

    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v4
      id: upload-artifact
