name: Build Jekyll Site

on:
  push:
    branches: ["!main"]
  workflow_dispatch:
  pull_request:

concurrency:
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/_build/
